/* confdefs.h */
#define PACKAGE_NAME "SILE"
#define PACKAGE_TARNAME "sile"
#define PACKAGE_VERSION "0.9.1"
#define PACKAGE_STRING "SILE 0.9.1"
#define PACKAGE_BUGREPORT "simon@simon-cozens.org"
#define PACKAGE_URL ""
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_LUA_H 1
#define HAVE_LUALIB_H 1
#define HAVE_LAUXLIB_H 1
#define HAVE_LUACONF_H 1
#define SILE_PATH "/usr/local/share/sile"
